### PR TITLE
Remove libqgtk3.so and other platformthemes that may lead to crashes

### LINKED ISSUE #150: Crash at startup on Ubuntu 20.04
```
$ ./AppImageUpdate-x86_64.AppImage
AppImageUpdate version 1-alpha (commit cb611d8), build 431 built on 2020-04-07 21:47:19 UTC
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(AppRun.wrapped:5738): Gtk-WARNING **: 11:58:11.580: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Fatal error reading PNG image file: bad parameters to zlib (gdk-pixbuf-error-quark, 0)
Aborted (core dumped)

```

### PR DESCRIPTION
**Pull request by probonopd**
Closes #150

### CODE REVIEW

**Comment by probonopd** [comment]
Getting

```
-- Running input plugin: qt -- 

Running process: /tmp/AppImageUpdate-build-F1P5tL/linuxdeploy-plugin-qt-x86_64.AppImage --appdir AppImageUpdate.AppDir

munmap_chunk(): invalid pointer

resources/build-appimages.sh: line 78:  8203 Aborted                 (core dumped) ./linuxdeploy-"$ARCH".AppImage --appdir 
```

**Comment by TheAssassin** [comment]
There's no reason to believe this is a good idea, other than some random experiments in #150. Mind to explain why how these are causing a crash? I think it was you who suggested to bundle these platform themes in the first place, so it would be appreciated if you could explain why they now fail, and whether there's changes needed in tools like linuxdeploy-plugin-qt (if it's a global issue, others could benefit from a solution as well).

**Review by TheAssassin — CHANGES_REQUESTED** [review]
See above.

**Comment by probonopd** [comment]
While I don't fully understand yet why they fail for some users, they do seem to be problematic, as removing them fixes the problems various users have reported.

And I was advocating for deploying libqgtk2* (without its dependencies - like Scribus is doing), not libqgtk3*. Actually it would be a good test if the affected users could try the Scribus AppImage and see if they experience the same crash with it.

**Comment by TheAssassin** [comment]
Possibly related: https://github.com/AppImage/AppImageUpdate/issues/151#issuecomment-688556817.

**Comment by probonopd** [comment]
Two years later, I was writing the exact same PR again when I found this.

We are getting lots and lots of error reports since years of AppImageUpdate crashing due to Gtk errors, and I am now sick and tired of it. Let's just remove all and everything related to Gtk and call it a day.

Unfortunately it seems that the LinuxDeploy plugin for Qt is what pulls this Gtk stuff in and there seems to be no obvious way to disable it...

**Comment by probonopd** [comment]
Please retry with https://github.com/AppImage/AppImageUpdate/releases/tag/continuous.

**Pull request closed without merging**
