### PR TITLE
Replace objdump

### PR DESCRIPTION
**Pull request by TheAssassin**
Implements changes suggested in #65. Downloads AppImageKit sources, builds a micro library from the ELF related code, and uses that library to read ELF sections.

### CODE REVIEW

**Comment by TheAssassin** [comment]
CC @antony-jr

**Comment by antony-jr** [comment]
My Bad :smile:  I forgot to make the **PR** , Looks Professional.  But Why not just add the elf source files instead of downloading it from AppImageKit ?  , If you do a custom build for Qt I suggest you use [QtAppImageUpdateInformation](https://github.com/antony-jr/QAIUpdateInformation) , Makes the Qt App more solid. ( Only uses the Qt5 Framework and uses Pure C++ Implementation of **mmap!** , Signals and Slots too :+1:   )

**Comment by TheAssassin** [comment]
@antony-jr because that adds maintenance overhead. If you watched AppImageKit, you might have noticed https://github.com/AppImage/AppImageKit/issues/669, which describes a couple of bugs in exactly that code. Copy-pasting source code between projects always adds maintenance overhead, and adds a lot of error potential (e.g., you forget to update one out of 10 projects, ...).

**Comment by antony-jr** [comment]
>  Copy-pasting source code between projects always adds maintenance overhead, and adds a lot of error potential (e.g., you forget to update one out of 10 projects, ...).

Yeah , That really happend a lot in my case. Good Thinking :+1:  Later then...

**Pull request merged**
